#TP2 exo5 question 4

PREFIX album:<http://www.m1ws.com/album#>
PREFIX personne:<http://www.m1ws.com/personne#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT ?nomalbum ?photo
FROM <exo3_data.rdf>
WHERE {
   { ?uri album:apournom_album ?nomalbum .
    ?uri album:lesphotos ?photo .
    ?photo rdf:type album:Photo_exterieur . } 
    
    UNION 
    { ?uri album:apournom_album ?nomalbum .
    ?uri album:lesphotos ?photo .
    ?photo rdf:type album:Photo_Portrait . }  
}

