PREFIX mv:<http://exemple.fr/mv#>

SELECT ?pers ?nompers ?acteurs ?nomacteur
FROM <personnes.n3>
FROM NAMED <acteurs.n3>
WHERE {
   ?pers mv:nom ?nompers.
   ?pers_dirige mv:nom "Walter Skinner".
   ?pers_dirige mv:dirige ?pers .
   GRAPH <acteurs.n3> {
       ?acteurs mv:nom ?nomacteur.
       ?acteurs mv:role ?pers.
   }
}